### ISSUE TITLE
Support new date-based gevent versioning

### ISSUE THREAD

**Issue by mands** [jgehrcke/gipc#101]
Hi,

It seems `gevent` has switched to a date-based versioning scheme post v1.5 - it would be great to support this in `gipc` so it can be used with  the newer gevent releases.

Thanks!

![image](https://user-images.githubusercontent.com/1010043/91167955-b0abfe00-e6cc-11ea-8351-5f79adc88c4c.png)

**Comment by jgehrcke** [comment]
I'll look into that, thank you!

**Comment by jgehrcke** [comment]
I think this has been addressed in the master branch.
