### ISSUE TITLE
Creating a pipe and passing to more than one process fails

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#11]
Originally reported by: **Dustin Oprea (Bitbucket: [dsoprea](https://bitbucket.org/dsoprea), GitHub: [dsoprea](https://github.com/dsoprea))**

----------------------------------------

Code:

```
#!python

import gipc

def _worker(r):
    pass

if __name__ == '__main__':
    with gipc.pipe() as (r, w):
        p1 = gipc.start_process(_worker, args=(r,))
        p2 = gipc.start_process(_worker, args=(r,))

        print("Joining.")

        p1.join()
        p2.join()
```

Error:

    Traceback (most recent call last):
      File "./multi.py", line 11, in <module>
        p2 = gipc.start_process(_worker, args=(r,))
      File "/Users/dustin/development/python/test/gipc_multiple/lib/python2.7/site-packages/gipc/gipc.py", line 260, in start_process
        h.close()
      File "/Users/dustin/development/python/test/gipc_multiple/lib/python2.7/site-packages/gipc/gipc.py", line 513, in close
        self._validate()
      File "/Users/dustin/development/python/test/gipc_multiple/lib/python2.7/site-packages/gipc/gipc.py", line 542, in _validate
        "GIPCHandle has been closed before.")
    gipc.gipc.GIPCClosed: GIPCHandle has been closed before.

There is no error if I don't pass the *r* pipe to the second process.

----------------------------------------
- Bitbucket: https://bitbucket.org/jgehrcke/gipc/issue/11

**Comment by jgehrcke** [comment]
Btw, @dsoprea, the project's home is now on GitHub. Do you still use gipc?

**Comment by chineking** [comment]
I think the queue implementation to gipc is quite useful for me.

I have implemented an Actor model system based on gipc, A few processes could be forked by `gipc.start_process`, each process has a duplex pipe connected to the main process, the actors created may locate on different processes, hence if one actor wants to send a message to another, the serialized message needs to be passed to the main process via the gipc pipe, the main process needs to deserialize part of the serialized message to check which destination process is, and then write the serialized message to the process via the specified gipc pipe, this is quite complicated and low-efficient.

If there is a queue, the queue size can be equal to the process size, a message from one actor could be serialized and written directly into the specified queue, this could make the code more neater in my opinion.

Thus I wonder if there is any plan for the queue implmentation, thanks.

**Comment by chineking** [comment]
I'd like to open a new issue to include the comment above.

**Comment by jgehrcke** [comment]
> I'd like to open a new issue to include the comment above.

Can't you do so? It should work. Thanks for the feedback!
