### ISSUE TITLE
test against newer 22.x gevent releases

### ISSUE THREAD

**Issue by jgehrcke** [jgehrcke/gipc#125]
@jamadden has done great work towards newer gevent releases recently. See https://www.gevent.org/changelog.html. The most recent release is `22.10.2 (2022-10-31)`.

**Comment by elderlabs** [comment]
I would like to use gipc with later versions of Python and gevent. Would it be possible to update the setup file, or is there something delaying progress?

Thank you.

**Comment by jgehrcke** [comment]
@elderlabs I just did a bit of CI work in https://github.com/jgehrcke/gipc/pull/126 to cover the latest gevent release (and more). I will make a new release soon. Until then you can use the current HEAD of `master` via `pip install git+https://github.com/jgehrcke/gipc`.

**Comment by elderlabs** [comment]
Perhaps I'm mistaken somewhere, but when installing the current `master`, it still requires an older version of `gevent`. Interestingly, this error was not thrown in my IDE, but was in my linux testing environment. Perhaps I've missed something.

`gipc 1.4.0 requires gevent<=21.12.0,>=1.5, but you have gevent 22.10.2 which is incompatible.`

**Comment by jgehrcke** [comment]
```
gipc 1.4.0 requires gevent<=21.12.0
```
That means you had still used the original 1.4.0 release, not the change that was recentty committed via https://github.com/jgehrcke/gipc/commit/3c9283dead41b341187f790b15c738d8c8ce277c.

I am going to release gipc 1.5.0 today btw, so then the changes will take effect by installing the latest gipc release from PyPI.

**Comment by jgehrcke** [comment]
Closing this as 'done' :)
https://github.com/jgehrcke/gipc/blob/master/CHANGELOG.rst#version-150-feb-27-2023
