### ISSUE TITLE
Python 3.12 + gevent 23 release?

### ISSUE THREAD

**Issue by madhavajay** [jgehrcke/gipc#130]
Hi @jgehrcke any chance of a release now that python 3.12 is stable and `gevent` CVEs have been fixed in `23.9.x`?

**Comment by alimm1995-seequent** [comment]
We also need to use `gevent 23.9.1`, due to the `gevent` CVE, but can't upgrade to it due to `gipc` dependencies. Is there something that we can help with around this release?

**Comment by jgehrcke** [comment]
Hey thank you for the question, and please excuse the late reply! 

The head of the master branch should be compatible (since landing #129). You should be able to install from there via `pip install git+https://github.com/jgehrcke/gipc`.

I will make a new (proper) release soon.

**Comment by jgehrcke** [comment]
More work happening in https://github.com/jgehrcke/gipc/pull/131.

**Comment by jgehrcke** [comment]
This is finally done! :) https://pypi.org/project/gipc/#history
