### ISSUE TITLE
[Windows] Can't run example on Windows 10, Python 3.6

### ISSUE THREAD

**Issue by akhilcacharya** [jgehrcke/gipc#36]
Example from [synchronization.py](https://github.com/jgehrcke/gipc/blob/master/examples/synchronization.py). Can't seem to use a pipe as a parameter for a spawned process. 

Error code: 

```
  File "test.py", line 33, in <module>
    main()
  File "test.py", line 13, in main
    p = gipc.start_process(writer_process, args=(cend,))
  File "C:\Anaconda\lib\site-packages\gipc\gipc.py", line 284, in start_process
    p.start()
  File "C:\Anaconda\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle gevent._semaphore.Semaphore objects
```

System: Windows 10, Python 3.6, gevent 1.2 (same failure on latest though), greenlet 4.1.2

**Comment by jgehrcke** [comment]
```
TypeError: can't pickle gevent._semaphore.Semaphore objects
```
The lock on a `GIPCHandle` is meant for itra-process synchronization. It lives on the heap of the current process and cannot even help synchronizing across multiple processes.

That is, we don't even need to try to pickle it to the child process.

One way to fix that could be to use the `_winapi_childhandle_after_createprocess_parent/child()` hook to remove the semaphore before starting the child, and to re-create a fresh one in the child.

Need to get CI set up on Windows again and then we can test this.

**Comment by jgehrcke** [comment]
This was indeed solved with https://github.com/jgehrcke/gipc/pull/66! Good news. I'll leave this open until we have a release.
