### ISSUE TITLE
start_process + pipe doesn't work?

### ISSUE THREAD

**Issue by jaddison** [jgehrcke/gipc#37]
Like a few of the other open issues state, `gipc.gipc.GIPCClosed: GIPCHandle has been closed before.` (and related) is a pretty common outcome. I cannot get any IPC to work via a `Pipe`. I feel that this project is pretty key for many people using gevent, but I'm not sure it's still functional? 

Are there plans to address the outstanding issues? As a FOSS dev myself, I know time isn't always available - but I'd love to see this project working.

Using Python 3.5.2, gipc 0.6.0, gevent 1.3.6, on Ubuntu 16.04.

**Comment by jaddison** [comment]
This is the problematic line: https://github.com/jgehrcke/gipc/blob/0b31f22e8704408ad45743778d0beea6da130de2/gipc/gipc.py#L349

If I comment that line out, things "just work".

**Comment by jaddison** [comment]
#11 explained the situation to me. Closing, not a bug.

**Comment by jgehrcke** [comment]
@jaddison glad to hear that you managed to get things working.

> I feel that this project is pretty key for many people using gevent

Thanks for your lovely feedback! I am planning to do another release soon. Did a bit of testing & maintenance work in `master`.

**Comment by jgehrcke** [comment]
Once the release is there please let me know if we should clarify things in the documentation even further.
