### ISSUE TITLE
Support gevent 1.4

### ISSUE THREAD

**Issue by jaddison** [jgehrcke/gipc#81]
installing my requirements.txt with `pip` (which has gevent==1.4.0 listed directly and gipc indirectly through a another package) yields this warning message, in beautiful bright red lettering:
```
gipc 1.0.0 has requirement gevent<1.4,>=1.2, but you'll have gevent 1.4.0 which is incompatible.
```

**Comment by jgehrcke** [comment]
Thanks. Let's see if CI is happy with the gevent 1.4 release (https://github.com/jgehrcke/gipc/pull/82). Then we can release a new gipc version with official support for gevent 1.4.

**Comment by jgehrcke** [comment]
Looks good! Patch landed in `master`. Will probably make a release shortly.

**Comment by jgehrcke** [comment]
https://pypi.org/project/gipc/1.0.1/

:sun_with_face:
