### ISSUE TITLE
support for gevent>=1.5.0 please

### ISSUE THREAD

**Issue by koreno** [jgehrcke/gipc#98]
It has been out for a couple of weeks, and we're getting:
```
ERROR: gipc 1.1.0 has requirement gevent<1.5,>=1.2, but you'll have gevent 1.5.0 which is incompatible.
```

**Comment by jgehrcke** [comment]
@koreno I will release a new version of gipc soon. Thanks for raising this issue. The preparational work was all done, tracked in https://github.com/jgehrcke/gipc/issues/86.

**Comment by ifiddes** [comment]
Is this going to be released as a new version soon?

**Comment by jgehrcke** [comment]
Thanks for asking @ifiddes -- I'll look into this soon again. Most of the work was done in https://github.com/jgehrcke/gipc/pull/91 and I am not quite sure anymore why I hesitated releasing. Sorry for the delay!

**Comment by jgehrcke** [comment]
Also see #101, about supporting gevent versions newer than 1.5.0.

**Comment by koreno** [comment]
@jgehrcke - any update? we're biting our fingernails!

**Comment by jgehrcke** [comment]
Thanks for the ping @koreno. Is gevent 1.5.0 itself a big win for you? There are new challenges with gevent 20.x compatibility, 1.5.0 support is easier to do. That would be a win -- yes?

**Comment by jgehrcke** [comment]
@koreno as I am always curious about what people use gipc for: what's your use case? : ) (having a cool use case in mind is of course additional huge motivation for doing work!).

**Comment by koreno** [comment]
Sure!
We're maintaining a large testing infrastructure for an enterprise storage
system.
We generally use a monkey-patched python-gevent environment, but some of
our tests need to spawn a child process to perform the IOs, as part of some
functions tests.
Without gipc, these forked processes inherit various monitoring greenlets
from the parent process, which is highly undesirable. It seems to inherit
various file descriptors as well.

(In fact we're running into such an issue now, even with gipc, so I'm
wondering if there's some rare edge-case or race-condition that allows it,
or maybe this has to do with changes in python/gevent)

- Ofer

**Comment by jgehrcke** [comment]
There's hope by the way that we can do gevent 20.x: https://github.com/gevent/gevent/pull/1728/files

**Comment by jgehrcke** [comment]
Just releases gipc 1.1.1, adding official support for gevent 1.5.0.
https://pypi.org/project/gipc/1.1.1/
https://github.com/jgehrcke/gipc/blob/master/CHANGELOG.rst#version-111-jan-03-2021

Supporting gevent 20.x is a little more work.

**Comment by kiarn** [comment]
Thanks @jgehrcke !
I will test to upgrade the requirements in Ajenti.

**Comment by jgehrcke** [comment]
@kiarn did things work out, did gipc 1.1.1 unblock you?

**Comment by kiarn** [comment]
@jgehrcke : thanks for asking, and sorry for the late answer, I'm under heavy load.

I still have a problem with the signal handler I'm not able to solve, but I think it belongs to another discussion, I will open an issue for this, even if I'm not sure it's an issue.
But all the rest is working fine, many thanks for your update.
